// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: api/grpc/statistic/data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ! Параметры рассылки статистики
type CPUUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserMode   float32 `protobuf:"fixed32,1,opt,name=user_mode,json=userMode,proto3" json:"user_mode,omitempty"`
	SystemMode float32 `protobuf:"fixed32,2,opt,name=system_mode,json=systemMode,proto3" json:"system_mode,omitempty"`
	Idle       float32 `protobuf:"fixed32,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *CPUUsage) Reset() {
	*x = CPUUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPUUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUUsage) ProtoMessage() {}

func (x *CPUUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUUsage.ProtoReflect.Descriptor instead.
func (*CPUUsage) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{0}
}

func (x *CPUUsage) GetUserMode() float32 {
	if x != nil {
		return x.UserMode
	}
	return 0
}

func (x *CPUUsage) GetSystemMode() float32 {
	if x != nil {
		return x.SystemMode
	}
	return 0
}

func (x *CPUUsage) GetIdle() float32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type DiskUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usage map[string]*DiskUsage_Usage `protobuf:"bytes,1,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{1}
}

func (x *DiskUsage) GetUsage() map[string]*DiskUsage_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type NodeUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usage map[string]*NodeUsage_Usage `protobuf:"bytes,1,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NodeUsage) Reset() {
	*x = NodeUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsage) ProtoMessage() {}

func (x *NodeUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsage.ProtoReflect.Descriptor instead.
func (*NodeUsage) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{2}
}

func (x *NodeUsage) GetUsage() map[string]*NodeUsage_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type IOStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usage map[string]*IOStat_Info `protobuf:"bytes,1,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *IOStat) Reset() {
	*x = IOStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOStat) ProtoMessage() {}

func (x *IOStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOStat.ProtoReflect.Descriptor instead.
func (*IOStat) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{3}
}

func (x *IOStat) GetUsage() map[string]*IOStat_Info {
	if x != nil {
		return x.Usage
	}
	return nil
}

type LoadAvg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min1  float32 `protobuf:"fixed32,1,opt,name=min1,proto3" json:"min1,omitempty"`
	Min5  float32 `protobuf:"fixed32,2,opt,name=min5,proto3" json:"min5,omitempty"`
	Min15 float32 `protobuf:"fixed32,3,opt,name=min15,proto3" json:"min15,omitempty"`
}

func (x *LoadAvg) Reset() {
	*x = LoadAvg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadAvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAvg) ProtoMessage() {}

func (x *LoadAvg) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAvg.ProtoReflect.Descriptor instead.
func (*LoadAvg) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{4}
}

func (x *LoadAvg) GetMin1() float32 {
	if x != nil {
		return x.Min1
	}
	return 0
}

func (x *LoadAvg) GetMin5() float32 {
	if x != nil {
		return x.Min5
	}
	return 0
}

func (x *LoadAvg) GetMin15() float32 {
	if x != nil {
		return x.Min15
	}
	return 0
}

type DiskUsage_Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fs      string  `protobuf:"bytes,1,opt,name=fs,proto3" json:"fs,omitempty"`
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
}

func (x *DiskUsage_Usage) Reset() {
	*x = DiskUsage_Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskUsage_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage_Usage) ProtoMessage() {}

func (x *DiskUsage_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage_Usage.ProtoReflect.Descriptor instead.
func (*DiskUsage_Usage) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{1, 1}
}

func (x *DiskUsage_Usage) GetFs() string {
	if x != nil {
		return x.Fs
	}
	return ""
}

func (x *DiskUsage_Usage) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type NodeUsage_Usage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fs      string  `protobuf:"bytes,1,opt,name=fs,proto3" json:"fs,omitempty"`
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
}

func (x *NodeUsage_Usage) Reset() {
	*x = NodeUsage_Usage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeUsage_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsage_Usage) ProtoMessage() {}

func (x *NodeUsage_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsage_Usage.ProtoReflect.Descriptor instead.
func (*NodeUsage_Usage) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{2, 1}
}

func (x *NodeUsage_Usage) GetFs() string {
	if x != nil {
		return x.Fs
	}
	return ""
}

func (x *NodeUsage_Usage) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type IOStat_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tps      float32 `protobuf:"fixed32,1,opt,name=tps,proto3" json:"tps,omitempty"`
	ReadKbs  float32 `protobuf:"fixed32,2,opt,name=read_kbs,json=readKbs,proto3" json:"read_kbs,omitempty"`
	WriteKbs float32 `protobuf:"fixed32,3,opt,name=write_kbs,json=writeKbs,proto3" json:"write_kbs,omitempty"`
}

func (x *IOStat_Info) Reset() {
	*x = IOStat_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_statistic_data_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOStat_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOStat_Info) ProtoMessage() {}

func (x *IOStat_Info) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_statistic_data_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOStat_Info.ProtoReflect.Descriptor instead.
func (*IOStat_Info) Descriptor() ([]byte, []int) {
	return file_api_grpc_statistic_data_proto_rawDescGZIP(), []int{3, 1}
}

func (x *IOStat_Info) GetTps() float32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *IOStat_Info) GetReadKbs() float32 {
	if x != nil {
		return x.ReadKbs
	}
	return 0
}

func (x *IOStat_Info) GetWriteKbs() float32 {
	if x != nil {
		return x.WriteKbs
	}
	return 0
}

var File_api_grpc_statistic_data_proto protoreflect.FileDescriptor

var file_api_grpc_statistic_data_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x08, 0x43, 0x50, 0x55, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x6b, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x69,
	0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x62, 0x0a, 0x0a, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3e, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x31, 0x0a,
	0x05, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x66, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x22, 0xe7, 0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x43,
	0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x62, 0x0a, 0x0a, 0x55, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x3e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x31, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x66, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x66, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0xfc, 0x01, 0x0a, 0x06, 0x49,
	0x4f, 0x53, 0x74, 0x61, 0x74, 0x12, 0x40, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x49,
	0x4f, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x5e, 0x0a, 0x0a, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x50, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74, 0x70,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6b, 0x62, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x4b, 0x62, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x6b, 0x62, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x62, 0x73, 0x22, 0x47, 0x0a, 0x07, 0x4c, 0x6f, 0x61,
	0x64, 0x41, 0x76, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x35,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x35, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x69, 0x6e, 0x31, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x69, 0x6e,
	0x31, 0x35, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_statistic_data_proto_rawDescOnce sync.Once
	file_api_grpc_statistic_data_proto_rawDescData = file_api_grpc_statistic_data_proto_rawDesc
)

func file_api_grpc_statistic_data_proto_rawDescGZIP() []byte {
	file_api_grpc_statistic_data_proto_rawDescOnce.Do(func() {
		file_api_grpc_statistic_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_statistic_data_proto_rawDescData)
	})
	return file_api_grpc_statistic_data_proto_rawDescData
}

var file_api_grpc_statistic_data_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_grpc_statistic_data_proto_goTypes = []any{
	(*CPUUsage)(nil),        // 0: api.grpc.statistic.data.CPUUsage
	(*DiskUsage)(nil),       // 1: api.grpc.statistic.data.DiskUsage
	(*NodeUsage)(nil),       // 2: api.grpc.statistic.data.NodeUsage
	(*IOStat)(nil),          // 3: api.grpc.statistic.data.IOStat
	(*LoadAvg)(nil),         // 4: api.grpc.statistic.data.LoadAvg
	nil,                     // 5: api.grpc.statistic.data.DiskUsage.UsageEntry
	(*DiskUsage_Usage)(nil), // 6: api.grpc.statistic.data.DiskUsage.Usage
	nil,                     // 7: api.grpc.statistic.data.NodeUsage.UsageEntry
	(*NodeUsage_Usage)(nil), // 8: api.grpc.statistic.data.NodeUsage.Usage
	nil,                     // 9: api.grpc.statistic.data.IOStat.UsageEntry
	(*IOStat_Info)(nil),     // 10: api.grpc.statistic.data.IOStat.Info
}
var file_api_grpc_statistic_data_proto_depIdxs = []int32{
	5,  // 0: api.grpc.statistic.data.DiskUsage.usage:type_name -> api.grpc.statistic.data.DiskUsage.UsageEntry
	7,  // 1: api.grpc.statistic.data.NodeUsage.usage:type_name -> api.grpc.statistic.data.NodeUsage.UsageEntry
	9,  // 2: api.grpc.statistic.data.IOStat.usage:type_name -> api.grpc.statistic.data.IOStat.UsageEntry
	6,  // 3: api.grpc.statistic.data.DiskUsage.UsageEntry.value:type_name -> api.grpc.statistic.data.DiskUsage.Usage
	8,  // 4: api.grpc.statistic.data.NodeUsage.UsageEntry.value:type_name -> api.grpc.statistic.data.NodeUsage.Usage
	10, // 5: api.grpc.statistic.data.IOStat.UsageEntry.value:type_name -> api.grpc.statistic.data.IOStat.Info
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_grpc_statistic_data_proto_init() }
func file_api_grpc_statistic_data_proto_init() {
	if File_api_grpc_statistic_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_statistic_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CPUUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_statistic_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DiskUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_statistic_data_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NodeUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_statistic_data_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IOStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_statistic_data_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LoadAvg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_statistic_data_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DiskUsage_Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_statistic_data_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*NodeUsage_Usage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_statistic_data_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*IOStat_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_statistic_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_grpc_statistic_data_proto_goTypes,
		DependencyIndexes: file_api_grpc_statistic_data_proto_depIdxs,
		MessageInfos:      file_api_grpc_statistic_data_proto_msgTypes,
	}.Build()
	File_api_grpc_statistic_data_proto = out.File
	file_api_grpc_statistic_data_proto_rawDesc = nil
	file_api_grpc_statistic_data_proto_goTypes = nil
	file_api_grpc_statistic_data_proto_depIdxs = nil
}
