// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/grpc/statistic/broadcaster.proto

package broadcaster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysStatBroadcaster_Subscribe_FullMethodName = "/api.grpc.statistic.statistic_broadcaster.SysStatBroadcaster/Subscribe"
)

// SysStatBroadcasterClient is the client API for SysStatBroadcaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ! API сервера статистики
type SysStatBroadcasterClient interface {
	// ! Подписа на рассылку статистики
	Subscribe(ctx context.Context, in *StatParams, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SysStat], error)
}

type sysStatBroadcasterClient struct {
	cc grpc.ClientConnInterface
}

func NewSysStatBroadcasterClient(cc grpc.ClientConnInterface) SysStatBroadcasterClient {
	return &sysStatBroadcasterClient{cc}
}

func (c *sysStatBroadcasterClient) Subscribe(ctx context.Context, in *StatParams, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SysStat], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SysStatBroadcaster_ServiceDesc.Streams[0], SysStatBroadcaster_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatParams, SysStat]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysStatBroadcaster_SubscribeClient = grpc.ServerStreamingClient[SysStat]

// SysStatBroadcasterServer is the server API for SysStatBroadcaster service.
// All implementations must embed UnimplementedSysStatBroadcasterServer
// for forward compatibility.
//
// ! API сервера статистики
type SysStatBroadcasterServer interface {
	// ! Подписа на рассылку статистики
	Subscribe(*StatParams, grpc.ServerStreamingServer[SysStat]) error
	mustEmbedUnimplementedSysStatBroadcasterServer()
}

// UnimplementedSysStatBroadcasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysStatBroadcasterServer struct{}

func (UnimplementedSysStatBroadcasterServer) Subscribe(*StatParams, grpc.ServerStreamingServer[SysStat]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSysStatBroadcasterServer) mustEmbedUnimplementedSysStatBroadcasterServer() {}
func (UnimplementedSysStatBroadcasterServer) testEmbeddedByValue()                            {}

// UnsafeSysStatBroadcasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysStatBroadcasterServer will
// result in compilation errors.
type UnsafeSysStatBroadcasterServer interface {
	mustEmbedUnimplementedSysStatBroadcasterServer()
}

func RegisterSysStatBroadcasterServer(s grpc.ServiceRegistrar, srv SysStatBroadcasterServer) {
	// If the following call pancis, it indicates UnimplementedSysStatBroadcasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysStatBroadcaster_ServiceDesc, srv)
}

func _SysStatBroadcaster_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SysStatBroadcasterServer).Subscribe(m, &grpc.GenericServerStream[StatParams, SysStat]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysStatBroadcaster_SubscribeServer = grpc.ServerStreamingServer[SysStat]

// SysStatBroadcaster_ServiceDesc is the grpc.ServiceDesc for SysStatBroadcaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysStatBroadcaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.grpc.statistic.statistic_broadcaster.SysStatBroadcaster",
	HandlerType: (*SysStatBroadcasterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SysStatBroadcaster_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/grpc/statistic/broadcaster.proto",
}
