name: OTUS Diploma

on:
  push:
    branches: 
      - diploma-dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.0

      - name: Linters
        uses: golangci/golangci-lint-action@v3

  # tests_by_makefile_linux:
  #   runs-on: ubuntu-latest
  #   steps:        
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.22.0

  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: make test
  #       run: make test

  #     - name: make server
  #       run: make server

  #     - name: make client
  #       run: make client

  # tests_by_makefile_windows:
  #   runs-on: windows-latest
  #   steps:        
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.22.0

  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: make test
  #       run: make test

  #     - name: make server
  #       run: make server

  #     - name: make client
  #       run: make client

  # tests_by_makefile_macos:
  #   runs-on: macos-latest
  #   steps:        
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.22.0

  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: make test
  #       run: make test

  #     - name: make server
  #       run: make server

  #     - name: make client
  #       run: make client
